### ISSUE TITLE
ActionBroadcast error

### ISSUE THREAD

**Issue by bobpaige** [Argelbargel/sonarqube-multiproject-gradle-plugin#2]
We are stuck with Sonar 5.6 so I'm trying to use your plugin for our multi-project, but I get the following error:

FAILURE: Build failed with an exception.

* What went wrong:
org/gradle/listener/ActionBroadcast
> org.gradle.listener.ActionBroadcast

This appears before any other output, so I'm guessing Gradle is still analyzing the project. If I remove your plugin, I don't see this error.

Gradle: 4.0.1

Any ideas?

**Comment by sgargel** [comment]
Using `--stacktrace` is giving you more info?

**Comment by bobpaige** [comment]
Good point! I should have thought of that.

* What went wrong:
org/gradle/listener/ActionBroadcast
> org.gradle.listener.ActionBroadcast

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.NoClassDefFoundError: org/gradle/listener/ActionBroadcast
        at org.sonarqube.gradle.SonarQubePlugin.addBroadcaster(SonarQubePlugin.java:95)
        at org.sonarqube.gradle.SonarQubePlugin.apply(SonarQubePlugin.java:86)
        at org.sonarqube.gradle.SonarQubePlugin.apply(SonarQubePlugin.java:63)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:41)

**Comment by Argelbargel** [comment]
@bobpaige: i fear this is caused by an incompatiblity between the older sonarQube-plugin and gradle 4.x. Could you try using gradle 3.5.1?
